# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Backend base URL by flavor
# 10.0.2.2 es para el Emulador
INVENTAPP_BASE_URL_EMULATOR=http://10.0.2.2:8000/api/
# 127.0.0.1 es para Dispositivo Físico usando 'adb reverse tcp:8000 tcp:8000'
INVENTAPP_BASE_URL_DEVICE=http://127.0.0.1:8000/api/
