# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Backend base URLs (Producción en Render)
# Al ser una URL pública HTTPS, funcionará tanto en emulador como en dispositivo físico.
INVENTAPP_BASE_URL_EMULATOR=https://api-luis370.onrender.com/api/
INVENTAPP_BASE_URL_DEVICE=https://api-luis370.onrender.com/api/
